package core

import (
	"database/sql"
	"strconv"
	"strings"
)

// Result summarizes an executed SQL command.
type Result interface {
	// LastInsertId returns the integer generated by the database
	// in response to a command. Typically this will be from an
	// "auto increment" column when inserting a new row. Not all
	// databases support this feature, and the syntax of such
	// statements varies.
	LastInsertId() (int64, error)
}

// Row is the result of calling QueryRow to select a single row.
// Its cursor starts before the first row of the result set.
// Use Next to advance from row to row.
type Row interface {
	//Scan copies the columns from the matched row into the values pointed at by dest.
	// If more than one row matches the query, Scan uses the first row and discards the rest.
	// If no row matches the query, Scan returns ErrNoRows.
	Scan(destinations ...interface{}) error
}

// Rows is the result of a query.
// Its cursor starts before the first row of the result set.
// Use Next to advance from row to row.
type Rows interface {
	// Next moves to the next result.
	// It will be false if there isn't next result.
	Next() bool
	// Scan scans the result and save it to the destinations.
	Scan(destinations ...interface{}) error
}

// Transaction is an interface that models the standard transaction in
// `database/sql`.
//
// To ensure `TxFn` funcs cannot commit or rollback a transaction (which is
// handled by `WithTransaction`), those methods are not included here.
type Transaction interface {
	Exec(query string, args ...interface{}) (Result, error)
	Prepare(query string) (*sql.Stmt, error)
	Query(query string, args ...interface{}) (Rows, error)
	QueryRow(query string, args ...interface{}) Row
}

type DbHandler interface {
	Transaction
	Commit() error
	Rollback() error
}

// A Txfn is a function that will be called with an initialized `Transaction` object
// that can be used for executing statements and queries against a database.
type TxFn func(Transaction) error

// WithTransaction creates a new transaction and handles rollback/commit based on the
// error object returned by the `TxFn`
func WithTransaction(repo DbHandler, fn TxFn) (err error) {

	defer func() {
		if p := recover(); p != nil {
			// a panic occurred, rollback and repanic
			err = repo.Rollback()
			panic(p)
		} else if err != nil {
			// something went wrong, rollback
			err = repo.Rollback()
		} else {
			// all good, commit
			err = repo.Commit()
		}
	}()

	err = fn(repo)
	return
}

// A PipelineStmt is a simple wrapper for creating a statement consisting of
// a query and a set of arguments to be passed to that query.
type PipelineStmt struct {
	query string
	args  []interface{}
}

func NewPipelineStmt(query string, args ...interface{}) *PipelineStmt {
	return &PipelineStmt{query, args}
}

// Executes the statement within supplied transaction. The literal string `{LAST_INS_ID}`
// will be replaced with the supplied value to make chaining `PipelineStmt` objects together
// simple.
func (ps *PipelineStmt) Exec(tx Transaction, lastInsertId int64) (Result, error) {
	query := strings.Replace(ps.query, "{LAST_INS_ID}", strconv.Itoa(int(lastInsertId)), -1)
	return tx.Exec(query, ps.args...)
}

// Runs the supplied statements within the transaction. If any statement fails, the transaction
// is rolled back, and the original error is returned.
//
// The `LastInsertId` from the previous statement will be passed to `Exec`. The zero-value (0) is
// used initially.
func RunPipeline(tx Transaction, stmts ...*PipelineStmt) (Result, error) {
	var res Result
	var err error
	var lastInsId int64

	for _, ps := range stmts {
		res, err = ps.Exec(tx, lastInsId)
		if err != nil {
			return nil, err
		}

		lastInsId, err = res.LastInsertId()
		if err != nil {
			return nil, err
		}
	}

	return res, nil
}
